[package]
name = "knightrs"
version = "0.9.9"
authors = ["Sam Westerman <mail@sampersand.me>"]
edition = "2021"
description = "The Knight programming language, in Rust"
repository = "https://github.com/knight-lang/rust"
license = "MIT"

# keywords = []
# categories = []

[features]
default = ["extensions", "custom-types"]
multithreaded = [] # Enables multithreading support

extensions = [] # stuff that's not part of base knight
custom-types = ["extensions"] # Allows users to add custom types in


lax-compliance = [] # runs non-compliant code, but improves the speed.
check-container-length = []
unicode = [] # Allow all unicode, not just knight's strict charset
relaxed-integers = [] # makes them 64 bit and does wrap arounds instead of hard errors.


[dependencies]
rand = "0.8"
once_cell = "1.7"
lazy_static = "1.4"
clap = { version = "2.33", optional = true }
static_assertions = "1.1"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "doc_cfg"]

[[bin]]
name = "knight"
path = "src/main.rs"
# required-features = ["clap"]

