[package]
name = "knight-lang"
version = "0.1.0"
authors = ["Sam Westerman <mail@sampersand.me>"]
edition = "2018"

[features]
strict-text = []

[dependencies]
static_assertions = "*"
bitflags = "1.2"
once_cell = "1.7.2"
# cfg-if = { version = "1.0", optional = true }