[package]
name = "knightrs"
version = "0.8.12"
authors = ["Sam Westerman <mail@sampersand.me>"]
edition = "2021"
description = "The Knight programming language, in Rust"
repository = "https://github.com/knight-lang/rust"
license = "MIT"

# keywords = []
# categories = []

[features]
default = ["extensions"]

#######################################
##           Optimizations           ##
#######################################

# Leak strings for fast access later.
cache-strings = []

# Instead of propagating exceptions, abort when an error occurs.
abort-on-errors = []

# Enable all optimizations
optimized = ["abort-on-errors", "cache-strings"]

#######################################
##      `Unsafe`  Optimizations      ##
#######################################

# Indicates unsafe code is enabled; used to deny unsafe code otherwise.
unsafe-enabled = []

# Assume knight will be run in one thread.
#
# WARNING: this can cause undefined behaviour if multiple threads use knight.
unsafe-single-threaded = ["unsafe-enabled"]

# Assume that all knight programs are 100% well-defined.
#
# WARNING: This **will** cause undefined behaviour if anything goes wrong, such as a system call failing.
# This should be used with caution.
#
# If `abort-on-errors` is enabled, this will be ignored.
unsafe-reckless = ["unsafe-enabled"]

# Enable all optimizations for knight
#
# WARNING: Read the descriptions of each `unsafe` feature to prevent undefined behaviour.
unsafe-optimized = ["unsafe-single-threaded", "cache-strings", "unsafe-reckless"]

#######################################
##         Knight Extensions         ##
#######################################

# Allow programs to assign to non-variables by converting to value to a variable first.
assign-to-anything = []

# Enables the `V` function, which can be used to dynamically look variables up without `EVAL`.
variable-lookup = []

# Just enable all extensions.
extensions = ["assign-to-anything", "variable-lookup"]


#######################################
##          Spec Compliance          ##
#######################################

# Restrict source files and strings to the bytes defined in the Knight spec.
disallow-unicode = []

# Catch undefined integer arithmetic
checked-overflow = []

# Use `i32` for numbers, which is the minimum required range.
strict-numbers = []

# Ensure BLOCK return values are handled correctly.
strict-block-return-value = []

# Exactly follow knight specs.
strict-compliance = ["strict-numbers", "checked-overflow", "disallow-unicode", "strict-block-return-value"]

[dependencies]
rand = "0.8"
once_cell = "1.7"
lazy_static = "1.4"
cfg-if = "1.0"
clap = { version = "2.33", optional = true }
tap = "1.0"

[[bin]]
name = "knight"
path = "src/main.rs"
required-features = ["clap"]
