[package]
name = "knightrs"
version = "0.8.12"
authors = ["Sam Westerman <mail@sampersand.me>"]
edition = "2021"
description = "The Knight programming language, in Rust"
repository = "https://github.com/knight-lang/rust"
license = "MIT"

# keywords = []
# categories = []

[features]
default = ["extensions"]

#######################################
##           Optimizations           ##
#######################################

# Leak strings for fast access later.
cache-strings = []

# Instead of propagating exceptions, abort when an error occurs.
abort-on-errors = []

# Enable all optimizations
optimized = ["abort-on-errors", "cache-strings"]

#######################################
##      Disabling Optimizations      ##
#######################################
multithreaded = []

#######################################
##      `Unsafe`  Optimizations      ##
#######################################


# Indicates unsafe code is enabled; used to deny unsafe code otherwise.
unsafe-enabled = []

# Assume knight will be run in one thread.
#
# WARNING: this can cause undefined behaviour if multiple threads use knight.
unsafe-single-threaded = ["unsafe-enabled"]

# Assume that all knight programs are 100% well-defined.
#
# WARNING: This **will** cause undefined behaviour if anything goes wrong, such as a system call failing.
# This should be used with caution.
#
# If `abort-on-errors` is enabled, this will be ignored.
unsafe-reckless = ["unsafe-enabled"]

# Enable all optimizations for knight
#
# WARNING: Read the descriptions of each `unsafe` feature to prevent undefined behaviour.
unsafe-optimized = ["unsafe-single-threaded", "cache-strings", "unsafe-reckless"]

#######################################
##        Disabling Extensions       ##
#######################################

# Disables the use of `EVAL`.
eval-function = []

# Causes `GET` and `SUBSTITUTE` to return errors instead of empty strings.
out-of-bounds-errors = []

# Enables the use of arrays
arrays = []

# Dividing strings by a string will split on that string.
split-strings = ["arrays"]

string-formatting = ["arrays"]

extensions = ["eval-function", "arrays", "split-strings", "string-formatting"]

# Just disable all extensions.
no-extensions = ["out-of-bounds-errors"]


#######################################
##          Spec Compliance          ##
#######################################

forbid-trailing-tokens = []

# Restrict source files and strings to the bytes defined in the Knight spec.
strict-charset = [] # TODO: make this work

# Catch undefined integer arithmetic
checked-overflow = []

# Use `i32` for numbers, which is the minimum required range.
strict-numbers = []

# Ensure BLOCK return values are handled correctly.
strict-block-return-value = []

# Exactly follow knight specs.
strict-compliance = [
	"strict-numbers",
	"checked-overflow",
	"forbid-trailing-tokens",
	"strict-charset",
	"strict-block-return-value",
	"no-extensions",
]

[dependencies]
rand = "0.8"
once_cell = "1.7"
lazy_static = "1.4"
cfg-if = "1.0"
clap = { version = "2.33", optional = true }
tap = "1.0"
static_assertions = "1.1"

[[bin]]
name = "knight"
path = "src/main.rs"
# required-features = ["clap"]
