[package]
name = "knightrs"
version = "0.8.11"
authors = ["Sam Westerman <mail@sampersand.me>"]
edition = "2018"
description = "The Knight programming language, in Rust"
repository = "https://github.com/knight-lang/rust"
license = "MIT"

# keywords = []
# categories = []

[features]
default = []
# default = ["cache-strings"]

# Leak strings for fast access later.
cache-strings = []

# Restrict source files and strings to the bytes defined in the Knight spec.
disallow-unicode = []

# Catch undefined integer arithmetic
checked-overflow = []

# Use `i32` for numbers, which is the minimum required range.
strict-numbers = []

# Ensure BLOCK return values are handled correctly.
strict-block-return-value = []

# Exactly follow knight specs.
strict-compliance = ["strict-numbers", "checked-overflow", "disallow-unicode", "strict-block-return-value"]

custom-types = []

# Assume knight will be run in one thread.
#
# WARNING: this can cause undefined behaviour if multiple threads use knight.
unsafe-single-threaded = []

# Enable all optimizations for knight
#
# WARNING: Read the descriptions of each feature to ensure no undefined behvaiour will occur.
unsafe-optimized = ["unsafe-single-threaded", "cache-strings"]

[dependencies]
rand = "0.8"
once_cell = "1.7"
lazy_static = "1.4"
parking_lot = "0.11"
clap = "2.33"
cfg-if = "1.0"
static_assertions="1.1"
try-traits = "0.1.1"
