[package]
name = "knightrs"
version = "0.8.11"
authors = ["Sam Westerman <mail@sampersand.me>"]
edition = "2018"
description = "The Knight programming language, in Rust"
repository = "https://github.com/knight-lang/rust"
license = "MIT"

# keywords = []
# categories = []

[features]
default = ["cache-strings"]

#######################################
##           Optimizations           ##
#######################################

# Leak strings for fast access later.
cache-strings = []

# Instead of propagating exceptions, abort when an error occurs.
abort-on-errors = []

# Enable all optimizations
optimized = ["abort-on-errors", "cache-strings"]

#######################################
##      `Unsafe`  Optimizations      ##
#######################################

# Assume knight will be run in one thread.
#
# WARNING: this can cause undefined behaviour if multiple threads use knight.
unsafe-single-threaded = []

# Assume that all knight programs are 100% well-defined.
#
# WARNING: This **will** cause undefined behaviour if anything goes wrong, such as a system call failing.
# This should be used with caution.
#
# If `abort-on-errors` is enabled, this will be ignored.
unsafe-reckless = []

# Enable all optimizations for knight
#
# WARNING: Read the descriptions of each `unsafe` feature to prevent undefined behaviour.
unsafe-optimized = ["unsafe-single-threaded", "cache-strings", "unsafe-reckless"]

#######################################
##          Spec Compliance          ##
#######################################

# Restrict source files and strings to the bytes defined in the Knight spec.
disallow-unicode = []

# Catch undefined integer arithmetic
checked-overflow = []

# Use `i32` for numbers, which is the minimum required range.
strict-numbers = []

# Ensure BLOCK return values are handled correctly.
strict-block-return-value = []

# Exactly follow knight specs.
strict-compliance = ["strict-numbers", "checked-overflow", "disallow-unicode", "strict-block-return-value"]

[dependencies]
rand = "0.8"
once_cell = "1.7"
lazy_static = "1.4"
parking_lot = "0.11"
cfg-if = "1.0"
clap = { version = "2.33", optional=true }

[[bin]]
features=["a"]
name = "main"
path = "src/main.rs"
required-features = ["clap", "optimized"]