[package]
name = "knightrs-bytecode"
version = "0.1.0"
edition = "2021"
default-run = "knightrs-bytecode"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0"
safe-transmute = "0.11"
thiserror = "2.0"
static_assertions = "1.1"
indexmap = "2.7"
rand = "0.8"
likely_stable = "0.1.2"
crossbeam-epoch = "0.9"

[features]
multithreaded = []
extensions = []
compliance = []
custom-types = ["extensions"]
stacktrace = [] # TODO: remove knight-debugging
qol = ["stacktrace"] # Enables debugging information fro knight
embedded = []
floats = []

# If enabled, support knight-2.0.1 features
knight_2_0_1 = []

all-extensions = ["extensions", "custom-types"]
iffy-extensions = ["extensions"]
all-iffy-extensions = ["all-extensions", "iffy-extensions"]
strict-compliance = ["compliance"]

# default = ["qol"]
default = ["extensions", "compliance", "qol", "embedded", "knight_2_0_1"] # the defaults just when testing
