[package]
name = "knights-bytecode"
version = "0.1.0"
edition = "2021"
default-run = "knights-bytecode"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0"
safe-transmute = "0.11"
thiserror = "2.0"
static_assertions = "1.1"
indexmap = "2.7"

[features]
multithreaded = []
extensions = []
compliance = []
custom-types = ["extensions"]
stacktrace = [] # TODO: remove knight-debugging
convenience = ["stacktrace"] # Enables debugging infromation fro knight

all-extensions = ["extensions", "custom-types"]
iffy-extensions = ["extensions"]
all-iffy-extensions = ["all-extensions", "iffy-extensions"]
strict-compliance = ["compliance"]

default = ["extensions", "compliance","convenience"] # convenience should be default
